# Generated by Django 5.2.8 on 2025-11-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
