# Generated by Django 5.2.8 on 2025-11-19 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='request_datetime',
            new_name='scheduled_at',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('CAREER', '진로상담'), ('ROBOT', '로봇기술'), ('CODING', '코딩질문'), ('OTHER', '기타')], default='CAREER', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='method',
            field=models.CharField(choices=[('OFFLINE', '대면상담'), ('ONLINE', '비대면상담')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('PENDING', '신청완료'), ('APPROVED', '상담예정'), ('COMPLETED', '상담완료'), ('CANCELED', '취소됨')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
