# Generated by Django 5.2.8 on 2025-11-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_rename_request_datetime_consultation_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('CAREER', '진로상담'), ('CODING', '코딩질문'), ('OTHER', '기타')], default='CAREER', max_length=20),
        ),
    ]
