# Generated by Django 5.2.8 on 2025-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=255, verbose_name='수업명'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('RECRUITING', '선생님 배정 중'), ('OPEN', '수강 신청 중'), ('IN_PROGRESS', '수업 진행 중'), ('CLOSED', '마감')], default='RECRUITING', max_length=20),
        ),
    ]
