# Generated by Django 5.2.8 on 2025-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='관심분야'),
        ),
    ]
