# Generated by Django 5.2.8 on 2025-11-19 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('lecture', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='lecture.lecture'),
        ),
    ]
